import type { AvatarId } from "@repo/protocol";

/**
 * Pixel-art sprite data for the 24 playable characters.
 *
 * Each sprite is a 12x12 grid of palette indices, written as 12 strings of 12
 * characters so the art is legible in source. "." is transparent (the chosen
 * background colour shows through); every other character keys into that
 * sprite's own `palette`.
 *
 * Hand-drawn glyphs beat generated noise here: these are the faces players
 * pick as their identity, so they need to be recognisable at 28px in a lobby
 * seat. Replacing a sprite is a data-only edit — nothing else reads the grid.
 */
export interface Sprite {
  /** Palette-index -> CSS colour. Keys are the characters used in `rows`. */
  palette: Record<string, string>;
  /** 12 rows of 12 characters. */
  rows: string[];
}

/* Shared inks, so characters read as one set rather than 24 unrelated icons. */
const K = "#14161c"; // outline / near-black
const W = "#ffffff";

export const SPRITES: Record<AvatarId, Sprite> = {
  flame: {
    palette: { a: "#ffd24a", b: "#ff8a1e", c: "#e33d16", k: K },
    rows: [
      ".....cc.....",
      "....cbc.....",
      "...cbbcc....",
      "...cbbbc....",
      "..cbabbbc...",
      "..cbaabbc...",
      ".cbaaabbbc..",
      ".cbaaaabbc..",
      ".cbaaaaabc..",
      "..cbaaaabc..",
      "...cbbbbc...",
      "....cccc....",
    ],
  },
  parrot: {
    palette: { a: "#e03b2c", b: "#f5a524", c: "#2f7fd0", k: K, w: W },
    rows: [
      "....aaaa....",
      "...aaaaaa...",
      "..aawwaaa...",
      "..aawkaabbb.",
      "..aaaaaabb..",
      "...aaaaaa...",
      "..aacccaa...",
      "..aaccccaa..",
      "..aaccccaa..",
      "...aaaaaa...",
      "....aaaa....",
      "....b..b....",
    ],
  },
  ghost: {
    palette: { a: "#cfe4ee", b: "#9fc0d2", k: K },
    rows: [
      "...aaaaa....",
      "..aaaaaaa...",
      ".aaaaaaaaa..",
      ".aakaakaaa..",
      ".aakaakaaa..",
      ".aaaaaaaaa..",
      ".aaaaaaaaa..",
      ".aabaaabaa..",
      ".aaaaaaaaa..",
      ".aaaaaaaaa..",
      ".abaabaaba..",
      "..a.aa.a.a..",
    ],
  },
  agent: {
    palette: { a: "#39527c", b: "#22334f", c: "#0f1218", w: "#8fb8e8", k: K },
    rows: [
      "...aaaaaa...",
      "..aaaaaaaa..",
      ".aabbbbbbaa.",
      ".abcccccca..",
      ".abcwccwcba.",
      ".abcccccca..",
      ".aabccccbaa.",
      ".aaabbbbaaa.",
      "aaaabbbbaaaa",
      "aaabbbbbbaaa",
      "aabbbbbbbbaa",
      "aab......baa",
    ],
  },
  pizza: {
    palette: { a: "#f2c14e", b: "#e0392b", c: "#d98e2b", k: K },
    rows: [
      "....cccc....",
      "...caaaac...",
      "...caabac...",
      "..caaaaaac..",
      "..cabaaabc..",
      ".caaaaaaaac.",
      ".caaabaaaac.",
      ".caabaaabac.",
      "..caaaaaac..",
      "...caaaac...",
      "....caac....",
      ".....cc.....",
    ],
  },
  banana: {
    palette: { a: "#f5d547", b: "#d9ab21", k: K, w: W },
    rows: [
      "......kk....",
      ".....kaak...",
      "....kaabk...",
      "...kaaabk...",
      "..kaaaabk...",
      "..kawaabk...",
      "..kawkabk...",
      "..kaaaabk...",
      "..kaaabk....",
      "..kaabk.....",
      "...kbk......",
      "....k.......",
    ],
  },
  crystal: {
    palette: { a: "#7ad7f0", b: "#2f8fd0", c: "#1b5a8c", k: K },
    rows: [
      ".....a......",
      "....aba.....",
      "...abbba....",
      "..abbcbba...",
      "..abbcbba...",
      ".abbccbbba..",
      ".abbccbbba..",
      "..abbcbba...",
      "..abbcbba...",
      "...abbba....",
      "....aba.....",
      ".....a......",
    ],
  },
  mushroom: {
    palette: { a: "#e0392b", b: "#f5f0e6", k: K },
    rows: [
      "...kkkkk....",
      "..kaabaak...",
      ".kabbbbaak..",
      ".kaabbbaak..",
      "kaaabbaaaak.",
      "kabaaaabaak.",
      "kaaaaaaaaak.",
      ".kkkkkkkkk..",
      "..kbbbbbk...",
      "..kbkbkbk...",
      "..kbbbbbk...",
      "...kkkkk....",
    ],
  },
  mask: {
    palette: { a: "#f0e0d0", b: "#c98a6a", k: K },
    rows: [
      "...kkkkk....",
      "..kaaaaak...",
      ".kaaaaaaak..",
      ".kakaakaak..",
      ".kaaaaaaak..",
      ".kabaaabak..",
      ".kaabbbaak..",
      ".kaaaaaaak..",
      ".kabbbbbak..",
      ".kaabababk..",
      "..kaaaaak...",
      "...kkkkk....",
    ],
  },
  penguin: {
    palette: { a: "#1c2430", b: "#f5f5f0", c: "#f5a524", k: K },
    rows: [
      "...aaaaa....",
      "..aaaaaaa...",
      "..abbbbba...",
      "..abkbkba...",
      "..abbcbba...",
      ".aabbbbbaa..",
      ".aabbbbbaa..",
      ".aabbbbbaa..",
      ".aabbbbbaa..",
      "..abbbbba...",
      "...aaaaa....",
      "...cc.cc....",
    ],
  },
  frog: {
    palette: { a: "#5aa02c", b: "#3d7a1c", k: K, w: W },
    rows: [
      "..aa...aa...",
      ".awwa.awwa..",
      ".awka.awka..",
      ".aaaaaaaaa..",
      "aaaaaaaaaaa.",
      "aaaaaaaaaaa.",
      "abaaaaaaaba.",
      "abbaaaaabba.",
      ".abbbbbbba..",
      ".akkkkkkka..",
      "..aaaaaaa...",
      "...a...a....",
    ],
  },
  bunny: {
    palette: { a: "#f5f0ea", b: "#f0a0b0", k: K },
    rows: [
      "..a.....a...",
      "..aba...aba.",
      "..aba...aba.",
      "..aaa...aaa.",
      "...aaaaaaa..",
      "..aaaaaaaaa.",
      "..akaaaaaka.",
      "..aaaaaaaaa.",
      "..aaabbaaaa.",
      "...aaaaaaa..",
      "....aaaaa...",
      ".....aaa....",
    ],
  },
  bear: {
    palette: { a: "#a0703c", b: "#7a5228", c: "#d9b48a", k: K },
    rows: [
      "..bb...bb...",
      ".baab.baab..",
      ".baaaaaaab..",
      "baaaaaaaaab.",
      "baakaaakaab.",
      "baaaaaaaaab.",
      "baaacccaaab.",
      "baaackcaaab.",
      ".baacccaab..",
      ".baaaaaaab..",
      "..bbaaabb...",
      "....bbb.....",
    ],
  },
  squid: {
    palette: { a: "#4a7fd0", b: "#2f5aa8", k: K, w: W },
    rows: [
      "...aaaaa....",
      "..aaaaaaa...",
      ".aaaaaaaaa..",
      ".awwaaawwa..",
      ".awkaaakwa..",
      ".aaaaaaaaa..",
      ".aabaaabaa..",
      ".aaaaaaaaa..",
      "..aaaaaaa...",
      "..a.a.a.a...",
      ".ab.ab.ab...",
      ".a..a..a....",
    ],
  },
  roll: {
    palette: { a: "#f5f5f0", b: "#d2d2cb", c: "#8f8f88", k: K },
    rows: [
      "..kkkkkkkk..",
      ".kaaaaaaaak.",
      "kabbbbbbbbak",
      "kabkccckbbak",
      "kabkcccbbbak",
      "kabkccckbbak",
      "kabbbbbbbbak",
      "kaaaaaaaaaak",
      "kaaaaaaaaaak",
      "kaaaaaaaaaak",
      ".kaaaaaaaak.",
      "..kkkkkkkk..",
    ],
  },
  shades: {
    palette: { a: "#f5c518", b: "#d9a013", k: K, w: W },
    rows: [
      "...aaaaaa...",
      "..aaaaaaaa..",
      ".aaaaaaaaaa.",
      ".akkkakkkka.",
      ".akwkakkwka.",
      ".akkkakkkka.",
      ".aaaaaaaaaa.",
      ".aaaaaaaaaa.",
      ".akkkkkkkka.",
      ".awwwwwwwwa.",
      "..aaaaaaaa..",
      "...aaaaaa...",
    ],
  },
  rocket: {
    palette: { a: "#e8ecf2", b: "#c0c8d4", c: "#e0392b", k: K },
    rows: [
      ".....cc.....",
      "....caac....",
      "....caac....",
      "...caaaac...",
      "...cabbac...",
      "...cabbac...",
      "..ccaaaacc..",
      ".cccaaaaccc.",
      ".cc.caac.cc.",
      "....caac....",
      "....c..c....",
      ".....cc.....",
    ],
  },
  bolt: {
    palette: { a: "#f5d547", b: "#f0a81e", k: K },
    rows: [
      ".....kkk....",
      "....kaak....",
      "...kaabk....",
      "..kaabk.....",
      "..kaabk.....",
      ".kaaaaaak...",
      ".kaabbbbk...",
      "..kbbaak....",
      "....kaak....",
      "....kabk....",
      "....kbk.....",
      "....kk......",
    ],
  },
  blob: {
    palette: { a: "#4a5160", b: "#2c3240", k: K, w: W },
    rows: [
      "....aaaa....",
      "..aaaaaaaa..",
      ".aaaaaaaaaa.",
      ".aaaaaaaaaa.",
      ".awwaaawwaa.",
      ".awkaaakwaa.",
      ".aaaaaaaaaa.",
      ".aaaaaaaaaa.",
      ".aakkkkkaaa.",
      "baaaaaaaaaab",
      "bbaaaaaaaabb",
      ".bb.bbbb.bb.",
    ],
  },
  dino: {
    palette: { a: "#5f8a9a", b: "#436a78", k: K, w: W },
    rows: [
      ".....aaaaa..",
      "....aaaaaaa.",
      "....awaaaaa.",
      "....aaaaaaa.",
      "....aaa.....",
      "aaaaaaa.....",
      "aaaaaaaa....",
      "aaaaaaaa....",
      ".aaaaaaa....",
      "..aaaaa.....",
      "..ab.ba.....",
      "..ab.ba.....",
    ],
  },
  skull: {
    palette: { a: "#e8e4da", b: "#b8b0a0", k: K },
    rows: [
      "...aaaaaa...",
      "..aaaaaaaa..",
      ".aaaaaaaaaa.",
      ".akkaaakka..",
      ".akkaaakka..",
      ".aaaakaaaaa.",
      ".aaaakaaaaa.",
      "..aaaaaaaa..",
      "..akakaka...",
      "..aaaaaaa...",
      "...bbbbb....",
      "....bbb.....",
    ],
  },
  chick: {
    palette: { a: "#f5d547", b: "#f0a81e", k: K, w: W },
    rows: [
      "...aaaaaa...",
      "..aaaaaaaa..",
      ".aaaaaaaaaa.",
      ".awwaaawwaa.",
      ".awkaaakwaa.",
      ".aaaaaaaaaa.",
      ".aaakkkkaaa.",
      ".aabwwwwbaa.",
      ".aabwwwwbaa.",
      ".aaakkkkaaa.",
      "..aaaaaaaa..",
      "...bb..bb...",
    ],
  },
  crab: {
    palette: { a: "#e0603a", b: "#b8401f", k: K, w: W },
    rows: [
      "..a......a..",
      ".aba....aba.",
      "..aaaaaaaa..",
      ".aaaaaaaaaa.",
      "aawaaaaawaa.",
      "aakaaaaakaa.",
      "aaaaaaaaaaa.",
      "aaabbbbbaaa.",
      ".aaaaaaaaa..",
      "..aaaaaaa...",
      ".ab.a.a.ba..",
      ".a..a.a..a..",
    ],
  },
  spectre: {
    palette: { a: "#3ac8e0", b: "#1f8fa8", k: K, w: W },
    rows: [
      "...aaaaaa...",
      "..aaaaaaaa..",
      ".aaaaaaaaaa.",
      ".awwaaawwaa.",
      ".awkaaakwaa.",
      ".awwaaawwaa.",
      ".aaaaaaaaaa.",
      ".aaaaaaaaaa.",
      ".aaaaaaaaaa.",
      ".aaaaaaaaaa.",
      ".abaabaabaa.",
      ".a..aa..a...",
    ],
  },
};

/** Human-readable names, for tooltips and screen readers. */
export const SPRITE_NAMES: Record<AvatarId, string> = {
  flame: "Flame",
  parrot: "Parrot",
  ghost: "Ghost",
  agent: "Agent",
  pizza: "Pizza",
  banana: "Banana",
  crystal: "Crystal",
  mushroom: "Mushroom",
  mask: "Mask",
  penguin: "Penguin",
  frog: "Frog",
  bunny: "Bunny",
  bear: "Bear",
  squid: "Squid",
  roll: "Roll",
  shades: "Shades",
  rocket: "Rocket",
  bolt: "Bolt",
  blob: "Blob",
  dino: "Dino",
  skull: "Skull",
  chick: "Chick",
  crab: "Crab",
  spectre: "Spectre",
};
